# Generated by Django 3.1.1 on 2020-10-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='nombre',
            new_name='materia',
        ),
    ]
