# Generated by Django 3.1.1 on 2020-10-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201007_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docente'),
        ),
    ]
