# Generated by Django 3.1.1 on 2020-10-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201007_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'ordering': ['estudiante'], 'verbose_name': 'consulta', 'verbose_name_plural': 'consultas'},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='docente',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='grado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.grado'),
        ),
    ]
