# Generated by Django 3.1.1 on 2020-10-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201007_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['grado'], 'verbose_name': 'grado', 'verbose_name_plural': 'grados'},
        ),
    ]
