# Generated by Django 3.1.1 on 2020-10-15 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201007_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['id'], 'verbose_name': 'materia', 'verbose_name_plural': 'materias'},
        ),
        migrations.AddField(
            model_name='consulta',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grado'),
        ),
    ]
