# Generated by Django 3.1.1 on 2020-10-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201015_1220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name': 'consulta', 'verbose_name_plural': 'consultas'},
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='created_at',
        ),
        migrations.AlterModelTable(
            name='consulta',
            table='consulta',
        ),
    ]
