# Generated by Django 3.1.1 on 2020-10-15 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201015_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docentemateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia')),
            ],
            options={
                'verbose_name': 'docentemateria',
                'verbose_name_plural': 'docentematerias',
                'db_table': 'docentemateria',
            },
        ),
    ]
